// Generated by apps/video/tools/gen-types.mjs from specs/*.schema.json. Do not edit; run `pnpm run gen:types`.
/* eslint-disable */

/**
 * 專案層級定義與 scene 播放順序。scene 內容與狀態存於各自的 scene.json（SPEC §4.1）。
 */
export interface VideoProjectJson {
  specVersion: string;
  /**
   * 以 `x-` 開頭的欄位保留給使用者或第三方工具自訂，Agent 必須原樣保留。
   */
  project: {
    id: string;
    name: string;
    /**
     * 影片類型：product = 產品介紹（Skill product-video）；story = 把故事做成 SVG 動畫影片（Skill story-video）。
     */
    kind?: "product" | "story";
    /**
     * 影片的來源資料；至少要有哪些依 project.kind 而定。
     */
    sources: {
      productUrl?: string | null;
      /**
       * 產品網址要登入才看得到。為 true 時，使用者須先以 pnpm run login 在瀏覽器視窗自行登入，capture 才能執行（gate productLogin）。帳密不寫入任何檔案。
       */
      requiresLogin?: boolean;
      /**
       * 產品原始碼位置，唯讀輸入，可在專案外（相對或絕對路徑）。
       */
      sourceCodePath?: string | null;
      description?: string | null;
      /**
       * 故事全文、大綱或點子（kind 為 story 時使用）。整理後的定稿在 brief/story.md。
       */
      story?: string | null;
      /**
       * 風格參考影片（可選，SPEC §6.2 Step 2）。
       */
      referenceVideoUrl?: string | null;
    };
    /**
     * 故事的角色與各自的聲音（kind 為 story 時使用）。script.md 中以【name】開頭的行由該角色說；其餘為旁白，用 project.tts。
     */
    cast?: {
      /**
       * 英文小寫識別碼，也是美術資料夾名稱（@/assets/cast/<id>/）。
       */
      id: string;
      /**
       * script.md 中【】內使用的名字。
       */
      name: string;
      /**
       * 外型與個性，給畫圖與挑聲音參考。
       */
      description?: string;
      /**
       * 省略時沿用 project.tts.provider。
       */
      provider?: "edge-tts" | "azure" | "openai" | "elevenlabs" | "piper" | "system" | "manual";
      /**
       * 省略時沿用 project.tts.voice。
       */
      voice?: string;
      /**
       * 角色部件 SVG 所在資料夾，通常為 @/assets/cast/<id>/。
       */
      art?: string;
    }[];
    targetAudience?: string;
    /**
     * 製作中發現某段太趕時：auto = Agent 可自行在限度內調整 scene 長度並事後回報；ask = 每次先詢問使用者。
     */
    durationAdjust?: "auto" | "ask";
    /**
     * 動畫的使用方式（Skill script-guide.md#custom-motion）。allow = Agent 依需要使用動畫範本與自訂動畫；ask = 範本照用，從零寫的自訂動畫（visual.motion 模組、Manim 程式、新的 SVG 插圖，較耗時與 token）在分鏡審閱時逐段由使用者決定；deny = 不使用動畫。
     */
    customMotion?: "allow" | "deny" | "ask";
    /**
     * 影片風格與語氣（例如：專業簡報、活潑社群短片），與使用者確認後填寫。
     */
    style?: string;
    /**
     * BCP 47 語言標籤，例如 zh-TW、en、en-US。
     */
    language: string;
    /**
     * 由 /video-translate 產生時記錄來源專案（SPEC §4.4）。
     */
    translatedFrom?: {
      id: string;
      /**
       * BCP 47 語言標籤，例如 zh-TW、en、en-US。
       */
      language: string;
    };
    /**
     * 寬高須符合 aspectRatio（由 validate.mjs 檢查）。H.264 需偶數寬高。
     */
    format: {
      aspectRatio: "16:9" | "9:16" | "1:1" | "4:5";
      width: number;
      height: number;
      fps: 24 | 25 | 30 | 50 | 60;
      targetDurationSec?: number;
    };
    /**
     * BGM 設定，只在 assemble 階段使用（SPEC §7.5）。
     */
    audio?: {
      /**
       * 相對於專案根目錄；null 或檔案不存在時略過 BGM。
       */
      bgm?: string | null;
      bgmVolume?: number;
      ducking?: boolean;
    };
    /**
     * 字幕設定，只在 assemble 階段使用，不納入 scene 的 inputHash（SPEC §7.5）。
     */
    captions?: {
      mode?: "srt" | "burn" | "none";
      style?: {
        fontFamily?: string;
        fontSize?: number;
        position?: "bottom" | "middle" | "top";
      };
    };
    /**
     * 專案預設 TTS（SPEC §7.4），scene 可覆寫。
     */
    tts: {
      /**
       * 見 SPEC §7.4。
       */
      provider: "edge-tts" | "azure" | "openai" | "elevenlabs" | "piper" | "system" | "manual";
      voice?: string;
      /**
       * 連網 TTS 的使用者同意紀錄。
       */
      consent?: {
        onlineTts: boolean;
        /**
         * ISO 8601 / RFC 3339 日期時間，須含時區。
         */
        grantedAt?: string;
      };
    };
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^x-".
     */
    [k: string]: unknown;
  };
  /**
   * 陣列順序即影片播放順序。
   */
  scenes: {
    id: string;
    /**
     * scene 目錄，格式 scenes/{三位數}-{slug}。目錄編號為建立時的序號，不代表目前順序。
     */
    dir: string;
  }[];
  /**
   * SPEC §4.5。
   */
  status:
    | "initialized"
    | "analyzed"
    | "designed"
    | "script_generated"
    | "producing"
    | "ready_to_assemble"
    | "completed"
    | "failed";
  /**
   * ISO 8601 / RFC 3339 日期時間，須含時區。
   */
  updatedAt: string;
  /**
   * 最後寫入者：agent（Agent 經 state.mjs）、user（Web UI 或手動）、companion、mcp。
   */
  updatedBy: "agent" | "user" | "companion" | "mcp";
  /**
   * This interface was referenced by `VideoProjectJson`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}

/**
 * 單一 scene 的定義與狀態（SPEC §4.2）。路徑相對於 scene 目錄；以 `@/` 開頭則相對於專案根目錄。
 */
export interface SceneJson {
  id: string;
  title: string;
  purpose:
    | "hook"
    | "problem"
    | "solution"
    | "feature"
    | "how-it-works"
    | "benefit"
    | "social-proof"
    | "cta"
    | "opening"
    | "setup"
    | "conflict"
    | "climax"
    | "resolution"
    | "ending"
    | "custom";
  narration: {
    /**
     * 專案內的相對路徑，使用正斜線。不得為絕對路徑、不得含 `..` 片段、不得含反斜線。scene.json 中的路徑相對於該 scene 目錄；以 `@/` 開頭表示相對於專案根目錄（例如 `@/assets/logo.png`）。
     */
    scriptFile: string;
    /**
     * 省略時沿用 project.tts.provider。
     */
    provider?: "edge-tts" | "azure" | "openai" | "elevenlabs" | "piper" | "system" | "manual";
    /**
     * 省略時沿用 project.tts.voice。
     */
    voice?: string;
    speed?: number;
    /**
     * 專案內的相對路徑，使用正斜線。不得為絕對路徑、不得含 `..` 片段、不得含反斜線。scene.json 中的路徑相對於該 scene 目錄；以 `@/` 開頭表示相對於專案根目錄（例如 `@/assets/logo.png`）。
     */
    audioFile?: string;
  };
  /**
   * 以 `x-` 開頭的欄位保留給使用者或第三方工具自訂，Agent 必須原樣保留。
   */
  visual: {
    /**
     * web-capture：Playwright 錄製網頁操作；screenshot：靜態截圖 + 動效；motion-graphic：純動畫（可用 motion 指定自寫的動畫模組）；code：程式碼展示；user-asset：使用者提供的影片或圖片；manim：Agent 撰寫的 Manim（Python）動畫，先由 pnpm run manim 渲染成影片再當背景。
     */
    type: "web-capture" | "screenshot" | "motion-graphic" | "code" | "user-asset" | "manim";
    /**
     * 給人與 Agent 讀的畫面描述。
     */
    description: string;
    capture?: {
      url: string;
      /**
       * 省略時使用 project.format 的寬高。
       */
      viewport?: {
        width: number;
        height: number;
      };
      actions?: {
        do: "navigate" | "scroll" | "click" | "hover" | "type" | "highlight" | "script" | "wait";
        url?: string;
        selector?: string;
        text?: string;
        /**
         * script 動作在頁面中執行的 JavaScript 檔（例如在資料很少的報表頁填入示意資料）。需要 capture.domEditConsent。
         */
        file?: string;
        /**
         * scroll 的絕對捲動位置（px），與 selector 擇一。
         */
        y?: number;
        /**
         * wait 的毫秒數；highlight 時為框住後停留的毫秒數（預設 1200）。
         */
        ms?: number;
        /**
         * true 時把這個動作從開始到結束（含等待頁面穩定）整段從錄影剪掉。Agent 判斷該段畫面沒有意義時使用，例如單頁應用切換路由的過場、載入中的骨架畫面。
         */
        cut?: boolean;
      }[];
      /**
       * 使用者同意在錄製時以 script 動作修改頁面內容（例如填入示意資料）的紀錄。
       */
      domEditConsent?: {
        granted: boolean;
        /**
         * ISO 8601 / RFC 3339 日期時間，須含時區。
         */
        grantedAt?: string;
      };
    };
    /**
     * 程式碼展示，file 與 content 擇一。
     */
    code?: {
      /**
       * 專案內的相對路徑，使用正斜線。不得為絕對路徑、不得含 `..` 片段、不得含反斜線。scene.json 中的路徑相對於該 scene 目錄；以 `@/` 開頭表示相對於專案根目錄（例如 `@/assets/logo.png`）。
       */
      file?: string;
      content?: string;
      language: string;
      highlightLines?: number[];
    };
    asset?: {
      /**
       * 專案內的相對路徑，使用正斜線。不得為絕對路徑、不得含 `..` 片段、不得含反斜線。scene.json 中的路徑相對於該 scene 目錄；以 `@/` 開頭表示相對於專案根目錄（例如 `@/assets/logo.png`）。
       */
      src: string;
      kind: "image" | "video";
      trimStartSec?: number;
      trimEndSec?: number;
      fit?: "contain" | "cover";
    };
    /**
     * motion-graphic 的自訂動畫：Agent 撰寫的 JavaScript 模組（SVG、Canvas、GSAP、Three.js、GLSL 等），取代預設的漸層背景，elements 仍疊加在上面。模組要求見 Skill rendering-guide.md#motion。
     */
    motion?: {
      /**
       * ES module，預設匯出 setup(ctx)，回傳 seek(t)。通常放在 assets/motion.js。
       */
      file: string;
      /**
       * 模組匯入的共用檔案或資料夾（例如 @/assets/cast/fox/），納入 inputHash：這些檔案一改，scene 就需要重做。資料夾以 / 結尾，包含底下所有檔案。
       */
      uses?: string[];
    };
    /**
     * manim 型別的動畫：Agent 撰寫的 Manim Community（Python）程式，由 pnpm run manim 渲染成 assets/manim.mp4 當背景，elements 仍疊加在上面。寫法見 Skill rendering-guide.md#manim。
     */
    manim?: {
      /**
       * Python 檔，通常放在 assets/scene.py。
       */
      file: string;
      /**
       * 要渲染的 Scene 類別名稱。
       */
      class?: string;
      /**
       * 程式匯入或讀取的共用檔案或資料夾（例如 @/assets/manim/），納入 inputHash。資料夾以 / 結尾，包含底下所有檔案。
       */
      uses?: string[];
    };
    /**
     * 疊加在畫面上的元素。
     */
    elements?: {
      type: "text" | "image" | "video";
      /**
       * type = text 時的文字。
       */
      content?: string;
      /**
       * type = image / video 時的來源。
       */
      src?: string;
      /**
       * 出現時間（scene 內相對秒數）。
       */
      at: number;
      /**
       * 顯示秒數；省略則持續到 scene 結束。
       */
      duration?: number;
      /**
       * type = text 的字級。large / xl 放大，但會自動縮回到不超過兩行、不超出畫面。
       */
      size?: "normal" | "large" | "xl";
      animation?:
        "none" | "fadeIn" | "slideInLeft" | "slideInRight" | "slideInUp" | "slideInDown" | "zoomIn" | "typewriter";
      /**
       * 預設位置，或以畫面百分比指定的自訂座標（元素中心點）。
       */
      position?:
        | ("center" | "top" | "bottom" | "left" | "right" | "top-left" | "top-right" | "bottom-left" | "bottom-right")
        | {
            x: number;
            y: number;
          };
    }[];
    /**
     * 進場轉場；第一個 scene 的轉場會被忽略。
     */
    transitionIn?: "none" | "fade" | "slide-left" | "slide-right" | "wipe" | "zoom";
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^x-".
     */
    [k: string]: unknown;
  };
  /**
   * null：由旁白音長 + 0.5 秒決定；數值：強制秒數。幀數一律由 durationSec × fps 推得，不儲存。
   */
  durationSec: number | null;
  /**
   * SPEC §4.5。
   */
  status: "draft" | "assets_ready" | "rendering" | "rendered" | "approved" | "stale" | "failed";
  /**
   * 最近一次成功渲染的紀錄。stale 時保留舊紀錄以供比對。
   */
  render?: {
    /**
     * SPEC §4.2：對 scene.json（排除 status、render、error、attempts、locked、updatedAt、updatedBy）、旁白稿、scene 素材、project.format 計算。
     */
    inputHash: string;
    /**
     * 專案內的相對路徑，使用正斜線。不得為絕對路徑、不得含 `..` 片段、不得含反斜線。scene.json 中的路徑相對於該 scene 目錄；以 `@/` 開頭表示相對於專案根目錄（例如 `@/assets/logo.png`）。
     */
    outputFile: string;
    /**
     * ISO 8601 / RFC 3339 日期時間，須含時區。
     */
    renderedAt: string;
    actualDurationSec?: number;
  } | null;
  /**
   * true 時 Agent 不得修改此 scene，除非使用者明確要求。不納入 inputHash。
   */
  locked: boolean;
  error?: {
    step: "tts" | "capture" | "manim" | "render" | "validate" | "other";
    message: string;
    /**
     * ISO 8601 / RFC 3339 日期時間，須含時區。
     */
    at: string;
    /**
     * 給使用者的重試或修正建議。
     */
    hint?: string;
  } | null;
  /**
   * 連續失敗次數，成功後歸零。Agent 自動重試上限 2 次（SPEC §8.1 規則 10）。
   */
  attempts?: number;
  /**
   * ISO 8601 / RFC 3339 日期時間，須含時區。
   */
  updatedAt?: string;
  /**
   * 最後寫入者：agent（Agent 經 state.mjs）、user（Web UI 或手動）、companion、mcp。
   */
  updatedBy?: "agent" | "user" | "companion" | "mcp";
  /**
   * This interface was referenced by `SceneJson`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}

/**
 * Agent 目前在做什麼、是否在等使用者回覆（SPEC §9.2）。只有 Agent 寫入、網頁只讀；不納入版本控制。專案建立前就可以存在（與 video.start.json 並列）。
 */
export interface VideoActivityJson {
  /**
   * 給使用者看的一句白話，例如「正在錄第 3 段的畫面」「分鏡寫好了，請在對話中確認」。
   */
  message: string;
  /**
   * true：Agent 停下來等使用者在對話中回覆（checkpoint、gate、提問）。
   */
  waitingForUser: boolean;
  /**
   * 目前的工作流程步驟或操作（workflow.json 的 id）；不在任何步驟時為 null。
   */
  step?: string | null;
  /**
   * 正在處理的 scene；沒有時為 null。
   */
  scene?: string | null;
  /**
   * ISO 8601 / RFC 3339 日期時間，須含時區。
   */
  updatedAt: string;
}
